### PR TITLE
<add> Added a new directory innit

### PR DESCRIPTION
**Pull request by JoelSmalls**
Yoooo check this out

### CODE REVIEW

**Comment by JoelSmalls** [comment]
@kamyar123

**Comment by vinthund** [comment]
bruh

**Comment by JoelSmalls** [comment]
bruh(2)

**Comment by CompEng0001** [comment]
bruh^n

**Review by vinthund — CHANGES_REQUESTED** [review]
this is rude tho :/

**Comment by ch6941r** [comment]
How much bruh could a bruhman bruh if a bruhman could say bruh?!

**Review by ad4646d — CHANGES_REQUESTED** [review]
add the absolute value of o

**Comment by JoelSmalls** [comment]
oh mang

**Pull request merged**
