### PR TITLE
<add> added my special things (no peeking)

### PR DESCRIPTION
**Pull request by ch6941r**
Pls look at my shizzle @ad4646d

### CODE REVIEW

**Comment by ad4646d** [comment]
adequate

**Comment by JoelSmalls** [comment]
this was sent on 4:20 pm

**Comment by JoelSmalls** [comment]
can @kamyar123 check out me section eh

**Comment by kamyar123** [comment]
happy

**Comment by vinthund** [comment]
yeehaw (i just wanna be involved)

**Comment by JoelSmalls** [comment]
welcome to alabama

**Pull request merged**
